2016-10-02 22:03:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE TABLE Nombres {
               nombre VARCHAR(300)
               PRIMARY KEY nombr[*]e"
Syntax error in SQL statement "CREATE TABLE Nombres {
               nombre VARCHAR(300)
               PRIMARY KEY nombr[*]e" [42000-192]
2016-10-02 22:03:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "}[*]"
Syntax error in SQL statement "}[*]"; SQL statement:
} [42000-192]
2016-10-02 22:04:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE TABLE NOMBRES (
               NOMBRE VARCHAR(300)
               PRIMARY KEY NOMBRE[*]
) "; se esperaba "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE NOMBRES (
               NOMBRE VARCHAR(300)
               PRIMARY KEY NOMBRE[*]
) "; expected "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE Nombres (
               nombre VARCHAR(300)
               PRIMARY KEY nombre
) [42001-192]
2016-10-02 22:04:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE TABLE NOMBRES (
               NOMBRE VARCHAR(300)
               PRIMARY KEY ([*]NOMBRE)
) "; se esperaba "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE NOMBRES (
               NOMBRE VARCHAR(300)
               PRIMARY KEY ([*]NOMBRE)
) "; expected "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE Nombres (
               nombre VARCHAR(300)
               PRIMARY KEY (nombre)
) [42001-192]
2016-10-02 22:04:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Columna "Pepe" no encontrada
Column "Pepe" not found; SQL statement:
INSERT INTO Nombres VALUES ("Pepe") [42122-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:259)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
